import React, { useMemo, useState } from 'react';
import { Activity, ArrowLeft, BarChart3, CheckCircle2, ClipboardCheck, Database, HeartPulse, LayoutDashboard, Moon, Play, Ruler, ShieldCheck, Sun, Users, XCircle } from 'lucide-react';
import WelcomeModal from '../components/WelcomeModal';
import { FITNESS_ENTITIES, FITNESS_TESTS, XMTA_SECTIONS } from './xmtaData';
import './xmta.css';

const ICONS = [LayoutDashboard,Users,Play,Database,Database,Ruler,HeartPulse,BarChart3,ClipboardCheck,CheckCircle2];

function SectionHead({ tag, title, children }) { return <header className="xmta-section-head"><span>{tag}</span><h2>{title}</h2>{children && <p>{children}</p>}</header>; }
function Metric({ value, label, tone='cyan' }) { return <div className={`xmta-metric tone-${tone}`}><strong>{value}</strong><span>{label}</span></div>; }

function Overview({ go }) { return <div>
  <SectionHead tag="CƠ SỞ DỮ LIỆU KIỂM TRA THỂ LỰC" title="XMTA — Quản Lý Kết Quả Thể Lực Quân Sự">Hệ thống mô hình hóa trọn quy trình từ đăng ký, sàng lọc y tế, thực hiện bài thi đến đối chiếu barem theo giới tính và độ tuổi.</SectionHead>
  <div className="xmta-hero"><div><span className="xmta-chip">FITNESS DATA COMMAND</span><h3>Mỗi kết quả đều có nguồn gốc, lượt thi và tiêu chuẩn đối chiếu.</h3><p>Dữ liệu thô được giữ nguyên; điểm quy đổi và xếp loại được xác định từ barem phù hợp thay vì ghi cứng vào môn thi.</p><button onClick={() => go('workflow')} className="btn btn-primary"><Play size={16}/> Khám phá quy trình</button></div><div className="xmta-radar"><Activity size={72}/><i/><i/><i/></div></div>
  <div className="xmta-metrics"><Metric value="6" label="Thực thể chuẩn hóa"/><Metric value="4" label="Môn thể lực mẫu" tone="violet"/><Metric value="3NF" label="Mức chuẩn hóa" tone="green"/><Metric value="100%" label="Qua sàng lọc trước thi" tone="amber"/></div>
  <div className="xmta-feature-grid">{[['Y tế là cổng bắt buộc','Không ghi nhận thành tích khi trạng thái y tế chưa ELIGIBLE.'],['Barem đa chiều','Phụ thuộc môn, giới tính, độ tuổi và chiều đánh giá.'],['Lưu nhiều lượt thi','Mỗi attempt là một bản ghi, không ghi đè lịch sử.'],['An toàn dữ liệu','Giám khảo nhập kết quả; trưởng ban mới được sửa barem.']].map(([a,b])=><article key={a}><h4>{a}</h4><p>{b}</p></article>)}</div>
  </div> }

function Actors() { const items=[['Thí sinh','Đăng ký đợt thi, khám sàng lọc và xem kết quả cá nhân.'],['Nhân viên y tế','Ghi huyết áp, nhịp tim và kết luận đủ điều kiện.'],['Giám khảo','Ghi thành tích thô theo môn và lượt thi được phân công.'],['Trưởng ban tổ chức','Mở đợt thi, quản lý barem và xác nhận báo cáo.'],['Cán bộ chỉ huy','Tra cứu, thống kê kết quả theo đơn vị.']]; return <div><SectionHead tag="RBAC & PHẠM VI DỮ LIỆU" title="Tác Nhân Và Quyền Hạn">Phân tách người khám, người chấm, người quản trị tiêu chuẩn và người khai thác báo cáo.</SectionHead><div className="xmta-actor-grid">{items.map(([a,b],i)=><article key={a}><span>0{i+1}</span><h3>{a}</h3><p>{b}</p></article>)}</div></div> }

function Workflow() { const steps=[['01','Tạo đợt kiểm tra','Khai báo thời gian, địa điểm và trạng thái.'],['02','Đăng ký thí sinh','Liên kết THISINH với DOTTHI qua DANGKYTHI.'],['03','Sàng lọc y tế','Đo huyết áp, nhịp tim; chỉ ELIGIBLE mới tiếp tục.'],['04','Ghi nhận lượt thi','Lưu thành tích thô, lần thi và giám khảo.'],['05','Đối chiếu barem','Chọn barem theo môn, giới tính và tuổi.'],['06','Công bố báo cáo','Tổng hợp điểm, đạt yêu cầu và xếp loại.']]; return <div><SectionHead tag="END TO END WORKFLOW" title="Quy Trình Kiểm Tra Có Kiểm Soát">Mọi bước đều để lại dấu vết và ngăn ghi kết quả sai điều kiện.</SectionHead><div className="xmta-timeline">{steps.map(([n,a,b])=><article key={n}><b>{n}</b><div><h3>{a}</h3><p>{b}</p></div></article>)}</div></div> }

function Entities() { return <div><SectionHead tag="LOGICAL MODEL 3NF" title="Sáu Thực Thể Cốt Lõi">Các bảng tách rõ dữ liệu danh mục, giao dịch, y tế và kết quả.</SectionHead><div className="xmta-entity-grid">{FITNESS_ENTITIES.map(e=><article key={e.name}><header><span>{e.code}</span><h3>{e.name}</h3></header><p>{e.title}</p><ul>{e.fields.map(f=><li key={f}>{f}</li>)}</ul></article>)}</div></div> }

function ERDiagram() { const paths=['M165 230 V315 H435 V400','M435 230 V400','M530 450 H610','M705 230 V400','M705 230 V325 H165 V400']; return <div><SectionHead tag="CONCEPTUAL ER" title="Mô Hình Quan Hệ Thể Lực">Sơ đồ giữ nguyên các quan hệ nhiều–nhiều đã được phân rã bằng bảng liên kết.</SectionHead><div className="xmta-er"><svg viewBox="0 0 1100 620"><defs><marker id="xmArrow" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="7" markerHeight="7" orient="auto"><path d="M0 0L10 5 0 10" fill="none" stroke="#42e5d1"/></marker></defs>{paths.map((d,i)=><path key={i} d={d} markerEnd="url(#xmArrow)"/>)}{FITNESS_ENTITIES.map((e,i)=>{const pos=[[70,130],[340,130],[610,130],[70,400],[340,400],[610,400]][i];return <foreignObject key={e.name} x={pos[0]} y={pos[1]} width="190" height="100"><div className="xmta-er-node"><b>{e.name}</b><span>{e.title}</span><small>{e.fields[0]}</small></div></foreignObject>})}<text x="550" y="70" textAnchor="middle">ERD QUẢN LÝ KIỂM TRA THỂ LỰC</text></svg></div></div> }

function MiniER({ human = false }) {
  const entities = human ? [
    { name:'THISINH', fields:'MaTS · HoTen · DonVi' },{ name:'DOTTHI', fields:'MaDot · NgayThi · DiaDiem' },
    { name:'MON_THE_LUC', fields:'MaMon · TenMon · DonViDo' },{ name:'BANG_KET_QUA', fields:'MaTS · MaDot · DiemChay · DiemXa' }
  ] : FITNESS_ENTITIES.map(e => ({ name:e.name, fields:e.fields.slice(0,3).join(' · ') }));
  const positions = human ? [[70,100],[390,100],[70,330],[390,330]] : [[35,90],[290,90],[545,90],[35,330],[290,330],[545,330]];
  const paths = human ? ['M220 145H390','M155 200V330','M475 200V330','M220 375H390'] : ['M130 190V270H385V330','M385 190V330','M480 380H545','M640 190V330','M640 190V270H130V330'];
  return <svg viewBox={human?'0 0 650 520':'0 0 780 520'} className={human?'xmta-er-canvas is-human':'xmta-er-canvas is-ai'}>
    <defs><marker id={human?'humanArrow':'aiArrow'} viewBox="0 0 10 10" refX="9" refY="5" markerWidth="7" markerHeight="7" orient="auto"><path d="M0 0L10 5 0 10" fill="none" stroke="currentColor"/></marker></defs>
    {paths.map((d,i)=><path key={i} d={d} markerEnd={`url(#${human?'humanArrow':'aiArrow'})`}/>)}
    {entities.map((e,i)=><foreignObject key={e.name} x={positions[i][0]} y={positions[i][1]} width="170" height="100"><div className="xmta-mini-node"><b>{e.name}</b><span>{e.fields}</span></div></foreignObject>)}
  </svg>;
}

function ERGallery() { return <div><SectionHead tag="HUMAN DESIGN vs AI REVIEW" title="Phòng Trưng Bày Mô Hình ER">Bản nhóm tự thiết kế được trình bày đơn sắc như sơ đồ Draw.io; bản AI rà soát dùng màu để phân vùng và hoàn thiện quan hệ.</SectionHead><div className="xmta-er-compare"><article className="is-human"><header><div><span>BẢN NHÓM TỰ THIẾT KẾ</span><h3>ER Ban Đầu · v0.1</h3></div><b>ĐƠN SẮC</b></header><MiniER human/><footer><strong>Nhóm tự làm:</strong> Xác định thí sinh, đợt thi, môn thể lực và bảng kết quả; đã nối được luồng nghiệp vụ chính nhưng còn gộp điểm môn vào một bảng.</footer></article><article className="is-ai"><header><div><span>AI HỖ TRỢ RÀ SOÁT</span><h3>ER Chuẩn Hóa · v1.0</h3></div><b>3NF</b></header><MiniER/><footer><strong>AI hỗ trợ:</strong> Tách DANGKYTHI cho y tế, KETQUACHITIET cho từng lượt và BAREMDIEM để tránh phụ thuộc bắc cầu.</footer></article></div><div className="xmta-review-strip"><div><b>GIỮ NGUYÊN TỪ BẢN NGƯỜI LÀM</b><span>Thí sinh · Đợt thi · Môn thể lực · Thành tích thô</span></div><div><b>AI ĐỀ XUẤT VÀ NHÓM CHẤP NHẬN</b><span>Sàng lọc y tế · Barem đa chiều · Nhiều lượt thi · RBAC</span></div></div></div> }

function Barem() { const [gender,setGender]=useState('NAM'); const [age,setAge]=useState(21); const [test,setTest]=useState(FITNESS_TESTS[0]); const [value,setValue]=useState(13.2); const score=useMemo(()=>{const base=test.direction==='LOWER' ? 10-Math.max(0,value-12)*1.8 : 5+(value-8)*.65; const adjusted=base-(age>30?.4:0)-(gender==='NU'?.25:0); return Math.max(0,Math.min(10,adjusted));},[test,value,age,gender]); return <div><SectionHead tag="DYNAMIC SCORING" title="Barem Và Quy Đổi Thành Tích">Minh họa nguyên tắc đối chiếu theo môn, giới tính, độ tuổi và chiều đánh giá.</SectionHead><div className="xmta-calculator"><div className="xmta-form"><label>Môn kiểm tra<select value={test.id} onChange={e=>setTest(FITNESS_TESTS.find(x=>x.id===e.target.value))}>{FITNESS_TESTS.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>Giới tính<select value={gender} onChange={e=>setGender(e.target.value)}><option>NAM</option><option>NU</option></select></label><label>Tuổi<input type="number" value={age} onChange={e=>setAge(+e.target.value)}/></label><label>Thành tích ({test.unit})<input type="number" step="0.01" value={value} onChange={e=>setValue(+e.target.value)}/></label></div><div className="xmta-score"><span>ĐIỂM QUY ĐỔI</span><strong>{score.toFixed(2)}</strong><b>{score>=8?'TỐT':score>=6.5?'KHÁ':score>=5?'ĐẠT':'CHƯA ĐẠT'}</b><small>Chiều đánh giá: {test.direction==='LOWER'?'Càng thấp càng tốt':'Càng cao càng tốt'}</small></div></div><div className="xmta-test-row">{FITNESS_TESTS.map(t=><article key={t.id} style={{'--test-color':t.accent}}><b>{t.name}</b><span>{t.unit}</span><small>{t.direction==='LOWER'?'↓ thấp hơn tốt hơn':'↑ cao hơn tốt hơn'}</small></article>)}</div></div> }

function Medical() { const [bp,setBp]=useState(120); const [pulse,setPulse]=useState(72); const eligible=bp>=90&&bp<=140&&pulse>=50&&pulse<=100; return <div><SectionHead tag="MEDICAL GATE" title="Sàng Lọc Y Tế Trước Kiểm Tra">Trigger nghiệp vụ chặn ghi KETQUACHITIET nếu DANGKYTHI chưa đủ điều kiện.</SectionHead><div className="xmta-medical"><div><label>Huyết áp tâm thu<input type="range" min="70" max="180" value={bp} onChange={e=>setBp(+e.target.value)}/><b>{bp} mmHg</b></label><label>Nhịp tim<input type="range" min="35" max="140" value={pulse} onChange={e=>setPulse(+e.target.value)}/><b>{pulse} bpm</b></label></div><section className={eligible?'is-eligible':'is-blocked'}>{eligible?<CheckCircle2 size={46}/>:<XCircle size={46}/>}<strong>{eligible?'ELIGIBLE':'NOT ELIGIBLE'}</strong><span>{eligible?'Được phép tham gia kiểm tra':'Khóa chức năng ghi kết quả'}</span></section></div></div> }

function Results() { const rows=[['HV001','Nguyễn Minh Anh','Đại đội 1','8.20','Tốt'],['HV014','Trần Quốc Bảo','Đại đội 2','7.15','Khá'],['HV027','Lê Hoàng Nam','Đại đội 1','5.80','Đạt'],['HV033','Phạm Đức Long','Đại đội 3','4.20','Chưa đạt']]; return <div><SectionHead tag="ANALYTICS" title="Kết Quả Và Báo Cáo Theo Đơn Vị">Dữ liệu minh họa từ view tổng hợp, hỗ trợ chỉ huy tra cứu toàn đơn vị.</SectionHead><div className="xmta-metrics"><Metric value="92%" label="Qua sàng lọc"/><Metric value="78%" label="Đạt yêu cầu" tone="green"/><Metric value="1.6" label="Lượt thi trung bình" tone="violet"/><Metric value="7.12" label="Điểm trung bình" tone="amber"/></div><div className="xmta-table"><table><thead><tr><th>Mã</th><th>Họ tên</th><th>Đơn vị</th><th>Điểm</th><th>Xếp loại</th></tr></thead><tbody>{rows.map(r=><tr key={r[0]}>{r.map((v,i)=><td key={i}>{v}</td>)}</tr>)}</tbody></table></div></div> }

function RelationalModel() { return <div><SectionHead tag="R1 — R6 · THIRD NORMAL FORM" title="Mô Hình Quan Hệ XMTA">Sáu quan hệ sau chuyển đổi từ ER, bảo toàn khóa và tách dữ liệu danh mục khỏi giao dịch.</SectionHead><div className="xmta-relation-list">{FITNESS_ENTITIES.map(e=><article key={e.name}><span>{e.code}</span><div><h3>{e.name}</h3><p>{e.fields.join(', ')}</p></div><b>{e.name==='DANGKYTHI'||e.name==='KETQUACHITIET'?'GIAO DỊCH':'DANH MỤC'}</b></article>)}</div><div className="xmta-normalization"><h3>Kiểm tra chuẩn hóa</h3><div><span><b>1NF</b> Thuộc tính nguyên tố, không gom nhiều kết quả trong một ô.</span><span><b>2NF</b> Mọi thuộc tính phụ thuộc đầy đủ khóa chính.</span><span><b>3NF</b> Barem được tách khỏi môn và kết quả, loại bỏ phụ thuộc bắc cầu.</span></div></div><Barem/></div> }

function Dictionary() { const rows=[['THISINH.NgaySinh','Ngày sinh','Tính tuổi tại ngày kiểm tra để chọn barem'],['MONTHELUC.ChieuDanhGia','Chiều đánh giá','HIGHER hoặc LOWER'],['DANGKYTHI.TrangThaiYTe','Trạng thái y tế','Chỉ ELIGIBLE được ghi kết quả'],['KETQUACHITIET.ThanhTichTho','Thành tích gốc','Không ghi đè sau quy đổi'],['KETQUACHITIET.LanThi','Số lượt','Từ 1 trở lên'],['BAREMDIEM.TuoiMin/TuoiMax','Khoảng tuổi','Không chồng lấn trong cùng môn và giới tính']]; return <div><SectionHead tag="DATA DICTIONARY" title="Từ Điển Dữ Liệu & Ràng Buộc">Các trường quan trọng được mô tả theo ý nghĩa nghiệp vụ, không phụ thuộc hệ quản trị CSDL.</SectionHead><div className="xmta-table xmta-dictionary"><table><thead><tr><th>Thuộc tính</th><th>Ý nghĩa</th><th>Miền giá trị / Quy tắc</th></tr></thead><tbody>{rows.map(r=><tr key={r[0]}>{r.map(x=><td key={x}>{x}</td>)}</tr>)}</tbody></table></div><Medical/></div> }

function AILog() { const sessions=[['01','Nhóm phân tích yêu cầu','Tự xác định 5 tác nhân, quy trình kiểm tra và bốn môn thể lực mẫu.'],['02','AI phản biện ER ban đầu','Phát hiện BANG_KET_QUA gộp cột, chưa lưu lần thi và chưa có cổng y tế.'],['03','Nhóm chọn lọc đề xuất','Chấp nhận DANGKYTHI, BAREMDIEM, KETQUACHITIET; bác bỏ mở rộng dinh dưỡng và huấn luyện.'],['04','AI kiểm tra chuẩn hóa','Rà soát 1NF, 2NF, 3NF và đề xuất các ca kiểm thử biên.']]; return <div><SectionHead tag="AI USAGE TRANSPARENCY" title="Nhật Ký Người Làm Và AI Hỗ Trợ">Nhóm giữ vai trò chủ thiết kế; AI chỉ phân tích, phản biện và đề xuất để nhóm đánh giá.</SectionHead><div className="xmta-ai-summary"><div><span>MÔ HÌNH AI</span><strong>Fable 5 + Astra 6</strong><small>Phân tích nghiệp vụ · Rà soát ER · Kiểm tra chuẩn hóa</small></div><div><span>TOKEN ƯỚC TÍNH</span><strong>38.600</strong><small>26.400 input · 12.200 output</small></div><div><span>NGUYÊN TẮC</span><strong>Human in control</strong><small>Không tự động chấp nhận đề xuất AI</small></div></div><div className="xmta-ai-log">{sessions.map(([n,a,b])=><article key={n}><b>{n}</b><div><h3>{a}</h3><p>{b}</p></div></article>)}</div><div className="xmta-ai-decisions"><section><h3>Đề xuất được chấp nhận</h3><ul><li>Tách sàng lọc y tế vào DANGKYTHI.</li><li>Lưu từng lượt trong KETQUACHITIET.</li><li>Tách barem theo giới tính và tuổi.</li><li>Giữ thành tích thô để phục vụ đối chiếu.</li></ul></section><section><h3>Đề xuất bị bác bỏ</h3><ul><li>Quản lý khẩu phần dinh dưỡng — ngoài phạm vi.</li><li>Theo dõi GPS khi chạy — không cần cho thiết kế CSDL.</li><li>Tự động xóa lượt thi kém — làm mất lịch sử.</li><li>Cho giám khảo sửa barem — sai phân quyền.</li></ul></section></div></div> }

function Scenarios() { const cases=[['Tuổi đúng mốc barem','Chọn đúng một khoảng tuổi, không chồng lấn.'],['Thành tích đúng ngưỡng','Quy đổi đúng điểm tại biên đạt/trượt.'],['Thi lại lần hai','Tạo bản ghi LanThi = 2, giữ nguyên lần một.'],['Chưa đạt y tế','Từ chối INSERT kết quả chi tiết.'],['20 giám khảo nhập đồng thời','Không ghi đè, kiểm tra deadlock và khóa.'],['Xóa đợt đã có kết quả','ON DELETE NO ACTION bảo toàn lịch sử.']]; return <div><SectionHead tag="TESTING & INTEGRITY" title="Sáu Tình Huống Kiểm Chứng">Các ca biên bám sát giai đoạn kiểm thử trong tài liệu.</SectionHead><div className="xmta-scenario-grid">{cases.map(([a,b],i)=><article key={a}><span>TC-{String(i+1).padStart(2,'0')}</span><CheckCircle2/><h3>{a}</h3><p>{b}</p></article>)}</div></div> }

function Conclusion() { return <div><SectionHead tag="KẾT LUẬN" title="XMTA Sẵn Sàng Cho Giai Đoạn Hiện Thực Hóa">Mô hình hoàn tất sáu giai đoạn từ phân tích yêu cầu đến kiểm thử và bảo trì.</SectionHead><div className="xmta-conclusion"><ShieldCheck size={60}/><h3>Thiết kế nhất quán, truy vết được và an toàn dữ liệu</h3><p>Sáu bảng cốt lõi đạt 3NF; dữ liệu y tế kiểm soát quyền dự thi; barem tách riêng; kết quả lưu theo từng lượt; quyền sửa tiêu chuẩn thuộc trưởng ban tổ chức.</p><div><span>Stored Procedure tính điểm</span><span>Trigger chặn sai điều kiện</span><span>View báo cáo tổng hợp</span><span>Backup hàng ngày</span></div></div></div> }

export default function XmtaApp({ onBack }) {
  const [section,setSection]=useState('overview'); const [theme,setTheme]=useState(()=>localStorage.getItem('smta-theme')||'dark');
  const go=id=>{setSection(id);window.scrollTo({top:0,behavior:'smooth'})};
  React.useEffect(()=>{document.documentElement.dataset.theme=theme;localStorage.setItem('smta-theme',theme)},[theme]);
  const content={overview:<Overview go={go}/>,actors:<Actors/>,workflow:<Workflow/>,entities:<Entities/>,er:<ERGallery/>,relational:<RelationalModel/>,dictionary:<Dictionary/>,scenarios:<><Scenarios/><Results/></>,ai:<AILog/>,conclusion:<Conclusion/>}[section];
  return <div className="xmta-app"><aside className="xmta-sidebar"><div className="xmta-brand"><div><Activity/></div><span><b>XMTA</b><small>QUẢN LÝ THỂ LỰC</small></span></div><nav>{XMTA_SECTIONS.map(([id,n,label],i)=>{const Icon=ICONS[i];return <button key={id} className={section===id?'active':''} onClick={()=>go(id)}><span>{n}</span><Icon size={17}/><b>{label}</b></button>})}</nav><button className="xmta-back" onClick={onBack}><ArrowLeft size={16}/> Đổi hệ thống</button></aside><div className="xmta-main"><header className="xmta-top"><div><span>XMTA v1.0</span><b>{XMTA_SECTIONS.find(x=>x[0]===section)?.[2]}</b></div><button className="theme-toggle" onClick={()=>setTheme(v=>v==='dark'?'light':'dark')}><span className={theme==='dark'?'is-active':''}><Moon size={14}/></span><span className={theme==='light'?'is-active':''}><Sun size={14}/></span></button></header><main key={section} className="xmta-content section-page-transition">{content}</main></div><WelcomeModal system="xmta"/></div>;
}
