import React, { useMemo, useState } from 'react';
import { Activity, ArrowLeft, BarChart3, CheckCircle2, ChevronRight, ClipboardCheck, Database, LayoutDashboard, Moon, Play, RotateCcw, Ruler, ShieldCheck, Sparkles, Sun, Users, X } from 'lucide-react';
import WelcomeModal from '../components/WelcomeModal';
import PresentationController from '../components/PresentationController';
import { FITNESS_AI_EXTENSIONS, FITNESS_ENTITIES, FITNESS_FIELD_META, FITNESS_RELATIONS, FITNESS_TESTS, XMTA_SECTIONS, parseFitnessField } from './xmtaData';
import './xmta.css';

const ICONS = [LayoutDashboard,Users,Play,Database,Database,Ruler,Activity,BarChart3,ClipboardCheck,CheckCircle2];

function SectionHead({ tag, title, children }) { return <header className="section-header xmta-section-head"><span className="section-tag">{tag}</span><h2 className="section-title">{title}</h2>{children && <p className="section-desc">{children}</p>}</header>; }
function Metric({ value, label, tone='cyan' }) { return <div className={`xmta-metric tone-${tone}`}><strong>{value}</strong><span>{label}</span></div>; }

function FieldChip({ entity, field, onExplain }) {
  const parsed=parseFitnessField(field); const meta=FITNESS_FIELD_META[entity.name]?.[parsed.name];
  return <button type="button" className={`xmta-field-chip ${parsed.key.includes('PK')?'is-pk':parsed.key.includes('FK')?'is-fk':''}`} onClick={e=>{e.stopPropagation();onExplain?.({entity,field:parsed.name,key:parsed.key,type:meta?.[0]||'Chưa xác định',reason:meta?.[1]||'Chưa có thuyết minh kiểu dữ liệu.'})}} title="Bấm để xem lý do chọn kiểu dữ liệu"><span>{parsed.name}{parsed.key&&` [${parsed.key}]`}</span><code>{meta?.[0]||'—'}</code></button>;
}

function SchemaModal({ entity, detail, onClose, onExplain }) {
  if (!entity && !detail) return null;
  return <div className="xmta-modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><section className="xmta-schema-modal" role="dialog" aria-modal="true"><button className="xmta-modal-close" onClick={onClose} aria-label="Đóng"><X size={19}/></button>{detail?<><span className="xmta-modal-kicker">{detail.entity.name}.{detail.field}</span><h3>{detail.type}</h3>{detail.key&&<b className="xmta-modal-key">{detail.key}</b>}<p>{detail.reason}</p></>:<><span className="xmta-modal-kicker">{entity.code} · {entity.kind}</span><h3>{entity.name}</h3><p>{entity.title}</p><div className="xmta-modal-fields">{entity.fields.map(field=><FieldChip key={field} entity={entity} field={field} onExplain={onExplain}/>)}</div><small>Bấm vào từng thuộc tính để xem lý do chọn kiểu SQL.</small></>}</section></div>;
}

function Overview({ go }) { return <div>
  <SectionHead tag="CƠ SỞ DỮ LIỆU KIỂM TRA THỂ LỰC" title="XMTA — Quản Lý Kết Quả Kiểm Tra Thể Lực Cấp Tiểu Đoàn">Hệ thống tin học hóa việc tổ chức, theo dõi và lưu trữ kết quả kiểm tra thể lực của học viên và cán bộ trong biên chế tiểu đoàn.</SectionHead>
  <div className="xmta-hero"><div><span className="xmta-chip">DATABASE DESIGN · VERIFIED</span><h3>Mỗi thành tích được lưu đúng quân nhân, môn, đợt và lần kiểm tra.</h3><p>XMTA đối chiếu thành tích thô với tiêu chuẩn của đơn vị, quản lý thi vét không ghi đè và tách rõ đề xuất AI với chỉ đạo của cán bộ chỉ huy.</p><button onClick={() => go('workflow')} className="btn btn-primary"><Play size={16}/> Khám phá quy trình</button></div><div className="xmta-radar"><Activity size={72}/><i/><i/><i/></div></div>
  <div className="xmta-metrics"><Metric value="9" label="Quan hệ chuẩn hóa"/><Metric value="12" label="Liên kết nghiệp vụ" tone="violet"/><Metric value="3NF / BCNF" label="Mức chuẩn hóa" tone="green"/><Metric value="4" label="Mức xếp loại" tone="amber"/></div>
  <div className="xmta-feature-grid">{[['Cơ cấu quân sự phân cấp','Tiểu đoàn → Đại đội → Lớp → Tiểu đội, liên kết đệ quy trong DON_VI.'],['Môn theo từng đợt','NOI_DUNG_DOT cấu hình môn bắt buộc, lựa chọn và thứ tự; không viết cứng bốn môn.'],['Tiêu chuẩn có phiên bản','Tra theo giới tính, nhóm tuổi và thời gian hiệu lực để không làm sai kết quả cũ.'],['Kết quả có ngữ cảnh','Phân biệt có mặt, vắng có phép, vắng không phép; lưu người chấm và thời điểm ghi nhận.']].map(([a,b])=><article key={a}><h4>{a}</h4><p>{b}</p></article>)}</div>
  </div> }

function Actors() { const items=[['Học viên và cán bộ','Thực hiện các môn được cấu hình cho từng đợt; vắng có phép và vắng không phép được ghi nhận riêng.'],['Cán bộ thể thao','Tổ chức đợt, đo thành tích và chịu trách nhiệm với thời điểm ghi nhận kết quả.'],['Cán bộ huấn luyện','Theo dõi kết quả từng môn, tình trạng thi vét và xu hướng tiến bộ qua nhiều đợt.'],['Chỉ huy đại đội','Tra cứu quân nhân, kết quả và phân công rèn luyện trong phạm vi đơn vị.'],['Chỉ huy tiểu đoàn','So sánh tỷ lệ đạt giữa đơn vị, kết luận và ghi chỉ đạo rèn luyện.']]; return <div><SectionHead tag="TÁC NHÂN & PHẠM VI QUẢN LÝ" title="Tác Nhân Và Quyền Hạn">Đúng phạm vi hồ sơ: cán bộ thể thao, cán bộ huấn luyện và chỉ huy đơn vị quản lý kết quả của quân nhân.</SectionHead><div className="xmta-actor-grid">{items.map(([a,b],i)=><article key={a}><span>0{i+1}</span><h3>{a}</h3><p>{b}</p></article>)}</div></div> }

function Workflow() { const steps=[['01','Tạo đợt và quy tắc','Khai báo loại đợt, thời gian, tỷ lệ môn đạt tối thiểu và số môn không đạt tối đa.'],['02','Cấu hình môn áp dụng','Chọn môn bắt buộc/lựa chọn và thứ tự trong NOI_DUNG_DOT; số môn có thể thay đổi theo đợt.'],['03','Xác định tiêu chuẩn','Tra giới tính, tuổi và phiên bản tiêu chuẩn có hiệu lực tại ngày kiểm tra.'],['04','Ghi nhận kết quả','Lưu thành tích, trạng thái tham gia, người chấm và thời điểm; hệ thống tự tính xếp loại môn.'],['05','Tổ chức thi vét','Chỉ tạo lần sau cho đúng môn chưa đạt; không ghi đè lịch sử lần trước.'],['06','Chốt và theo dõi','Tổng hợp theo quy tắc của đợt, so sánh tiến bộ và để chỉ huy ghi kết luận.']]; return <div><SectionHead tag="END TO END WORKFLOW" title="Quy Trình Kiểm Tra Có Kiểm Soát">Kết quả lần sau không ghi đè lần trước; toàn bộ lịch sử rèn luyện được bảo toàn.</SectionHead><div className="xmta-timeline">{steps.map(([n,a,b])=><article key={n}><b>{n}</b><div><h3>{a}</h3><p>{b}</p></div></article>)}</div></div> }

function Entities() { return <div><SectionHead tag="LOGICAL MODEL · 3NF / BCNF" title="Chín Quan Hệ Trong Mô Hình Chính Thức">Mô hình bổ sung danh sách môn theo đợt, tiêu chuẩn theo tuổi–giới tính–hiệu lực và ngữ cảnh ghi nhận kết quả.</SectionHead><div className="xmta-entity-grid">{FITNESS_ENTITIES.map(e=><article key={e.name}><header><span>{e.code}</span><h3>{e.name}</h3></header><p>{e.title}</p><ul>{e.fields.map(f=><li key={f}>{f}</li>)}</ul></article>)}</div></div> }

const HUMAN_ER_ENTITIES = FITNESS_ENTITIES.filter(entity=>entity.name!=='NOI_DUNG_DOT').map(entity=>{
  if(entity.name==='TIEU_CHUAN_MON') return {...entity,title:'Ngưỡng chung theo nhóm đối tượng',fields:['MaMon [PK, FK]','DoiTuongApDung [PK]','MucXepLoai [PK]','GiaTriNguong']};
  if(entity.name==='DOT_KIEM_TRA') return {...entity,title:'Đợt kiểm tra bốn môn cố định',fields:['MaDot [PK]','TenDot','NgayBatDau','NgayKetThuc']};
  if(entity.name==='KET_QUA_CHI_TIET') return {...entity,title:'Thành tích từng môn',fields:['MaDot [PK, FK]','MaQuanNhan [PK, FK]','MaMon [PK, FK]','ThanhTichTho']};
  return entity;
});

const AI_ER_ENTITIES = [
  FITNESS_ENTITIES[0],FITNESS_ENTITIES[1],FITNESS_ENTITIES[2],FITNESS_ENTITIES[3],FITNESS_ENTITIES[4],
  FITNESS_ENTITIES[5],FITNESS_ENTITIES[6],FITNESS_AI_EXTENSIONS[0],FITNESS_AI_EXTENSIONS[1],FITNESS_AI_EXTENSIONS[2],
  FITNESS_ENTITIES[7],FITNESS_ENTITIES[8]
];

function MiniER({ human = false, onSelectEntity }) {
  const [active,setActive]=useState(null);
  const entities=human?HUMAN_ER_ENTITIES:AI_ER_ENTITIES;
  const positions = human?[[35,70],[300,70],[300,285],[565,70],[830,70],[35,500],[565,500],[830,500]]:[[35,90],[300,90],[300,310],[565,90],[830,90],[35,550],[300,550],[565,310],[830,310],[35,310],[565,550],[830,550]];
  const links = [
    { from:'DON_VI',to:'DON_VI',d:'M35 115H15V245H70V215', label:'cấp trên / cấp dưới', x:18, y:270 },
    { from:'CAP_BAC',to:'QUAN_NHAN',d:'M405 215V285', label:'RankCapBac', x:418, y:252 },
    { from:'DON_VI',to:'QUAN_NHAN',d:'M245 145H270V355H300', label:'MaDonVi', x:210, y:334 },
    { from:'MON_KIEM_TRA',to:'TIEU_CHUAN_MON',d:'M775 145H830', label:'MaMon', x:785, y:130 },
    { from:'DOT_KIEM_TRA',to:'KET_QUA_CHI_TIET',d:'M140 500V450H670V430', label:'MaDot', x:392, y:438 },
    { from:'QUAN_NHAN',to:'KET_QUA_CHI_TIET',d:'M510 355H535V550H565', label:'MaQuanNhan', x:515, y:470 },
    { from:'MON_KIEM_TRA',to:'KET_QUA_CHI_TIET',d:'M670 215V500', label:'MaMon', x:682, y:360 },
    { from:'DOT_KIEM_TRA',to:'NOI_DUNG_DOT',d:'M140 500H300', label:'MaDot', x:190, y:486 },
    { from:'MON_KIEM_TRA',to:'NOI_DUNG_DOT',d:'M670 215V450H405V500', label:'MaMon', x:455, y:438 },
    { from:'QUAN_NHAN',to:'KET_QUA_CHI_TIET',d:'M510 355H535V550H565', label:'MaNguoiCham', x:512, y:520 },
    { from:'DOT_KIEM_TRA',to:'KET_QUA_TONG_HOP',d:'M140 500V470H935V500', label:'MaDot', x:790, y:458 },
    { from:'QUAN_NHAN',to:'KET_QUA_TONG_HOP',d:'M510 365H535V475H935V500', label:'MaQuanNhan', x:708, y:465 }
  ];
  if(!human) links.push(
    {from:'DOT_KIEM_TRA',to:'BUOI_KIEM_TRA',d:'M140 550V465H670V455',label:'MaDot',x:430,y:452},
    {from:'BUOI_KIEM_TRA',to:'PHAN_CONG_BUOI',d:'M775 380H830',label:'MaBuoi',x:785,y:365},
    {from:'QUAN_NHAN',to:'PHAN_CONG_BUOI',d:'M510 380H830',label:'MaCanBo',x:650,y:368},
    {from:'QUAN_NHAN',to:'CHI_SO_CO_THE',d:'M300 380H245',label:'MaQuanNhan',x:210,y:365}
  );
  const visibleNames=new Set(entities.map(entity=>entity.name));
  const visibleLinks=links.filter(link=>visibleNames.has(link.from)&&visibleNames.has(link.to));
  const related=new Set(visibleLinks.filter(link=>link.from===active||link.to===active).flatMap(link=>[link.from,link.to]));
  return <svg viewBox={`0 0 1075 ${human?690:770}`} className={human?'xmta-er-canvas is-human':'xmta-er-canvas is-ai'} aria-label={human?'Mô hình ER do nhóm tự vẽ':'Mô hình ER do AI rà soát'} onMouseLeave={()=>!human&&setActive(null)}>
    <defs><marker id={human?'humanArrow':'aiArrow'} viewBox="0 0 10 10" refX="9" refY="5" markerWidth="7" markerHeight="7" orient="auto"><path d="M0 0L10 5 0 10" fill="none" stroke="currentColor"/></marker><filter id="xmtaAiGlow"><feGaussianBlur stdDeviation="3" result="blur"/><feMerge><feMergeNode in="blur"/><feMergeNode in="SourceGraphic"/></feMerge></filter><pattern id="xmtaAiGrid" width="22" height="22" patternUnits="userSpaceOnUse"><path d="M22 0H0V22" fill="none" stroke="rgba(103,232,249,.055)"/></pattern></defs>
    {!human&&<><rect className="xmta-ai-grid" width="1075" height="770" fill="url(#xmtaAiGrid)"/><g className="xmta-ai-domain domain-core"><rect x="20" y="55" width="500" height="430" rx="18"/><text x="38" y="82">HỒ SƠ, TỔ CHỨC &amp; CHỈ SỐ NỀN</text></g><g className="xmta-ai-domain domain-test"><rect x="545" y="55" width="510" height="430" rx="18"/><text x="563" y="82">TIÊU CHUẨN, LỊCH &amp; PHÂN CÔNG</text></g><g className="xmta-ai-domain domain-result"><rect x="20" y="510" width="1035" height="235" rx="18"/><text x="38" y="540">NỘI DUNG ĐỢT &amp; KẾT QUẢ TRUY VẾT</text></g></>}
    <text className="xmta-diagram-title" x="537" y="35" textAnchor="middle">{human?'MÔ HÌNH ER — BẢN NHÓM TỰ VẼ':'MÔ HÌNH ER — BẢN AI RÀ SOÁT'}</text>
    {visibleLinks.map((link,i)=>{const highlighted=!human&&active&&(link.from===active||link.to===active);return <g className={`xmta-er-link ${active&&!highlighted&&!human?'is-dimmed':''} ${highlighted?'is-active':''}`} key={i}><path d={link.d} markerEnd={`url(#${human?'humanArrow':'aiArrow'})`}/><text x={link.x} y={link.y}>{link.label}</text><text className="cardinality" x={link.x-12} y={link.y-14}>1</text><text className="cardinality" x={link.x+64} y={link.y-14}>N</text></g>})}
    {entities.map((entity,i)=>{const isActive=active===entity.name;const isDimmed=!human&&active&&!related.has(entity.name);return <foreignObject key={entity.name} x={positions[i][0]} y={positions[i][1]} width="210" height="145"><button type="button" className={`xmta-mini-node kind-${entity.kind.toLowerCase().replace(' ','-')} ${isActive?'is-active':''} ${isDimmed?'is-dimmed':''}`} onMouseEnter={()=>!human&&setActive(entity.name)} onFocus={()=>!human&&setActive(entity.name)} onClick={()=>onSelectEntity?.(entity)} title={human?'Bản sơ đồ tĩnh do nhóm tự vẽ':'Rê để làm nổi quan hệ · Bấm để phóng to bảng'}><b>{entity.name}</b><small>{entity.title}</small><ul>{entity.fields.slice(0,human?4:6).map(field=><li key={field}>{field}</li>)}</ul>{!human&&<em>Rê để xem nối · Bấm để mở</em>}</button></foreignObject>})}
  </svg>;
}

function ERGallery() { const [expanded,setExpanded]=useState(null);const [detail,setDetail]=useState(null);const upgrades=[['8 → 12 bảng','AI thêm NOI_DUNG_DOT, BUOI_KIEM_TRA, PHAN_CONG_BUOI và CHI_SO_CO_THE.'],['Đợt → buổi cụ thể','Bản cũ chỉ biết khoảng ngày; AI quản lý ngày giờ, địa điểm và trạng thái từng buổi.'],['Người chấm → phân công vai trò','AI tách cán bộ chủ trì, giám sát, ghi kết quả để truy trách nhiệm.'],['Ngưỡng chung → tiêu chuẩn phiên bản','AI xét giới tính, tuổi và hiệu lực, tránh dùng quy định mới tính lại lịch sử.']];return <><div><SectionHead tag="KHÁC BIỆT NỘI DUNG · HUMAN vs AI" title="Hai Mô Hình Không Còn Cùng Một Nội Dung">Bản người vẽ tái hiện mô hình ban đầu từ báo cáo; bản AI đối chiếu cả hai tài liệu để phát hiện phần thiếu và đề xuất mở rộng có kiểm soát.</SectionHead><div className="xmta-content-delta">{upgrades.map(([a,b],i)=><article key={a}><span>+0{i+1}</span><h3>{a}</h3><p>{b}</p></article>)}</div><div className="xmta-er-compare"><article className="is-human"><header><div><span>BẢN NHÓM TỰ THIẾT KẾ · BASELINE</span><h3>ER Ban Đầu · 8 bảng</h3></div><b>CHƯA PHẢN BIỆN</b></header><div className="xmta-model-limit"><b>Giới hạn nội dung</b><span>4 môn cố định · Không có buổi kiểm tra · Không phân vai cán bộ · Tiêu chuẩn chưa có hiệu lực</span></div><div className="xmta-diagram-scroll"><MiniER human/></div><footer><strong>Người vẽ:</strong> quản lý được hồ sơ, đợt và kết quả cơ bản nhưng chưa mô tả đầy đủ khâu tổ chức kiểm tra trong thực tế.</footer></article><article className="is-ai"><header><div><span>AI ĐỐI CHIẾU 2 TÀI LIỆU · ENHANCED</span><h3>ER Đề Xuất · 12 bảng</h3></div><b>4 BẢNG MỚI</b></header><div className="xmta-ai-help"><Sparkles size={15}/> Rê vào bảng để truy vết quan hệ. Các bảng A10–A12 là phần AI bổ sung từ nghiệp vụ trong tài liệu.</div><div className="xmta-diagram-scroll"><MiniER onSelectEntity={setExpanded}/></div><footer><strong>AI cải tiến nội dung:</strong> thêm lịch theo buổi, phân công cán bộ ba vai trò, chỉ số cơ thể; đồng thời tách môn theo đợt và phiên bản hóa tiêu chuẩn.</footer></article></div><div className="xmta-er-legend"><span><i className="legend-catalog"/>Danh mục</span><span><i className="legend-business"/>Nghiệp vụ</span><span><i className="legend-reference"/>Tham chiếu</span><span><i className="legend-transaction"/>Giao dịch</span><b>Rê: truy vết quan hệ · Bấm: xem đầy đủ bảng và kiểu SQL</b></div><div className="xmta-review-strip"><div><b>NGƯỜI VẼ · MÔ HÌNH GỐC</b><span>8 bảng · Theo dõi kết quả cơ bản · Còn viết cứng nghiệp vụ</span></div><div><b>AI · MÔ HÌNH ĐỀ XUẤT</b><span>12 bảng · Tổ chức đến từng buổi · Truy trách nhiệm · Giữ lịch sử chuẩn</span></div></div></div><SchemaModal entity={expanded} detail={detail} onClose={()=>{setExpanded(null);setDetail(null)}} onExplain={value=>{setExpanded(null);setDetail(value)}}/></> }

function Barem() { const [group,setGroup]=useState('NAM_18_25'); const [test,setTest]=useState(FITNESS_TESTS[0]); const [value,setValue]=useState(75); const rating=useMemo(()=>{const good=test.direction==='LOWER'?value<=75:value>=12; const fair=test.direction==='LOWER'?value<=90:value>=9; const pass=test.direction==='LOWER'?value<=110:value>=6; return good?'GIỎI':fair?'KHÁ':pass?'ĐẠT':'KHÔNG ĐẠT';},[test,value]); return <div><SectionHead tag="THAM CHIẾU TIÊU CHUẨN" title="Đối Chiếu Theo Giới Tính Nhóm Tuổi Và Hiệu Lực">Minh họa cách chọn đúng phiên bản TIEU_CHUAN_MON tại ngày kiểm tra; không dùng tiêu chuẩn mới để tính lại kết quả cũ.</SectionHead><div className="xmta-calculator"><div className="xmta-form"><label>Môn kiểm tra<select value={test.id} onChange={e=>setTest(FITNESS_TESTS.find(x=>x.id===e.target.value))}>{FITNESS_TESTS.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>Giới tính và nhóm tuổi<select value={group} onChange={e=>setGroup(e.target.value)}><option>NAM_18_25</option><option>NU_18_25</option><option>NAM_26_35</option><option>NU_26_35</option></select></label><label>Thành tích ({test.unit})<input type="number" step="0.01" value={value} onChange={e=>setValue(+e.target.value)}/></label></div><div className="xmta-score"><span>XẾP LOẠI MÔN</span><strong>{rating}</strong><b>{group.replaceAll('_',' ')}</b><small>Quy tắc: {test.direction==='LOWER'?'NHO_HON_LA_TOT':'LON_HON_LA_TOT'}</small></div></div><div className="xmta-test-row">{FITNESS_TESTS.map(t=><article key={t.id} style={{'--test-color':t.accent}}><b>{t.name}</b><span>{t.unit}</span><small>{t.direction==='LOWER'?'↓ nhỏ hơn là tốt':'↑ lớn hơn là tốt'}</small></article>)}</div></div> }

function Results() { const rows=[['HV001','Nguyễn Minh Anh','Đại đội 1','DA_VET_DAT','ĐẠT'],['HV014','Trần Quốc Bảo','Đại đội 2','KHONG_THI_VET','KHÁ'],['HV027','Lê Hoàng Nam','Đại đội 1','CHO_THI_VET','KHÔNG ĐẠT'],['CB033','Phạm Đức Long','Tiểu đoàn bộ','KHONG_THI_VET','GIỎI']]; return <div><SectionHead tag="ANALYTICS" title="Kết Quả Và Báo Cáo Theo Đơn Vị">Dữ liệu minh họa từ KET_QUA_TONG_HOP, hỗ trợ chỉ huy tra cứu theo cây đơn vị và theo dõi tiến bộ qua nhiều đợt.</SectionHead><div className="xmta-metrics"><Metric value="Theo đợt" label="Số môn linh hoạt"/><Metric value="78%" label="Đạt yêu cầu" tone="green"/><Metric value="14" label="Chờ thi vét" tone="violet"/><Metric value="3NF" label="Dữ liệu báo cáo" tone="amber"/></div><div className="xmta-table"><table><thead><tr><th>Mã quân nhân</th><th>Họ tên</th><th>Đơn vị</th><th>Trạng thái thi vét</th><th>Xếp loại chung cuộc</th></tr></thead><tbody>{rows.map(r=><tr key={r[0]}>{r.map((v,i)=><td key={i}>{v}</td>)}</tr>)}</tbody></table></div></div> }

function RelationalComparison() { const [expanded,setExpanded]=useState(null); const [detail,setDetail]=useState(null); return <><div className="xmta-schema-compare"><article className="schema-human"><div>{FITNESS_ENTITIES.map(e=><p key={e.name}><strong>{e.name}</strong> ({e.fields.map((field,i)=>{const parsed=parseFitnessField(field);const meta=FITNESS_FIELD_META[e.name]?.[parsed.name];return <React.Fragment key={field}>{i>0&&', '}<button className="schema-human-field" onClick={()=>setDetail({entity:e,field:parsed.name,key:parsed.key,type:meta?.[0]||'Chưa xác định',reason:meta?.[1]||'Chưa có thuyết minh kiểu dữ liệu.'})}>{parsed.name} {parsed.key&&`[${parsed.key}]`} <code>{meta?.[0]}</code></button></React.Fragment>})})</p>)}</div><footer>Mỗi thuộc tính đã có kiểu SQL; bấm vào thuộc tính để xem lý do lựa chọn.</footer></article><article className="schema-ai"><header><span>AI RÀ SOÁT · LƯỢC ĐỒ CHUẨN HÓA</span><b>VERIFIED</b></header><div>{FITNESS_ENTITIES.map(e=><section key={e.name} role="button" tabIndex="0" onClick={()=>setExpanded(e)} onKeyDown={event=>(event.key==='Enter'||event.key===' ')&&setExpanded(e)} className={`schema-kind-${e.kind.toLowerCase().replace(' ','-')}`} title="Bấm để phóng to bảng"><h4><em>{e.code}</em>{e.name}<small>{e.kind}</small></h4><p>{e.fields.map(field=><FieldChip key={field} entity={e} field={field} onExplain={setDetail}/>)}</p></section>)}</div><footer>Bấm vào bảng nhỏ để phóng to; bấm vào thuộc tính để xem lý do chọn kiểu SQL.</footer></article></div><SchemaModal entity={expanded} detail={detail} onClose={()=>{setExpanded(null);setDetail(null)}} onExplain={value=>{setExpanded(null);setDetail(value)}}/></> }

function RelationalModel() { return <div><SectionHead tag="R1 — R9 · 3NF / BCNF" title="Mô Hình Quan Hệ XMTA">Chín quan hệ chính thức, trong đó NOI_DUNG_DOT giải quyết quan hệ nhiều–nhiều giữa đợt và môn kiểm tra.</SectionHead><RelationalComparison/><div className="xmta-table"><table><thead><tr><th>Liên kết</th><th>Thực thể cha</th><th>Thực thể con</th><th>Khóa ngoại</th><th>Ý nghĩa</th></tr></thead><tbody>{FITNESS_RELATIONS.map(r=><tr key={r[0]}>{r.map(x=><td key={x}>{x}</td>)}</tr>)}</tbody></table></div><div className="xmta-normalization"><h3>Kiểm tra chuẩn hóa</h3><div><span><b>1NF</b> Mỗi thuộc tính nguyên tử; danh sách môn theo đợt được tách riêng.</span><span><b>2NF</b> Thuộc tính của các quan hệ khóa ghép phụ thuộc đầy đủ toàn bộ khóa.</span><span><b>3NF / BCNF</b> Tiêu chuẩn có phiên bản, không ghi đè lịch sử khi quy định thay đổi.</span></div></div><Barem/></div> }

function Dictionary() { const rows=[['DON_VI.RankDonVi','Thứ bậc đơn vị','1: Tiểu đội · 2: Lớp · 3: Đại đội · 4: Tiểu đoàn'],['QUAN_NHAN.LoaiDoiTuong','Phân loại quân nhân','HOC_VIEN hoặc CAN_BO'],['NOI_DUNG_DOT.BatBuoc','Cấu hình môn theo đợt','1: bắt buộc · 0: lựa chọn'],['DOT_KIEM_TRA.LoaiDot','Loại tổ chức','DINH_KY · DOT_XUAT · PHUC_TRA'],['TIEU_CHUAN_MON.HieuLucTu','Phiên bản tiêu chuẩn','Ngày kiểm tra phải nằm trong khoảng hiệu lực'],['KET_QUA_CHI_TIET.TrangThaiThucHien','Trạng thái tham gia','CO_MAT · VANG_CO_PHEP · VANG_KHONG_PHEP · MIEN_GIAM'],['KET_QUA_CHI_TIET.LanThi','Lần kiểm tra','1: chính thức · 2 trở lên: thi vét'],['KET_QUA_CHI_TIET.XepLoaiMon','Kết quả hệ thống tính','GIOI · KHA · DAT · KHONG_DAT'],['KET_QUA_TONG_HOP.TrangThaiThiVet','Tình trạng thi vét','KHONG_THI_VET · CHO_THI_VET · DA_VET_DAT · VET_KHONG_DAT'],['KET_QUA_TONG_HOP.DeXuatAI','Gợi ý tự động','Tách biệt hoàn toàn với GhiChuChiHuy']]; return <div><SectionHead tag="DATA DICTIONARY" title="Từ Điển Dữ Liệu & Ràng Buộc">Các thuộc tính quan trọng được mô tả theo ý nghĩa nghiệp vụ, không phụ thuộc hệ quản trị CSDL.</SectionHead><div className="xmta-table xmta-dictionary"><table><thead><tr><th>Thuộc tính</th><th>Ý nghĩa</th><th>Miền giá trị / Quy tắc</th></tr></thead><tbody>{rows.map(r=><tr key={r[0]}>{r.map(x=><td key={x}>{x}</td>)}</tr>)}</tbody></table></div></div> }

function AILog() { const sessions=[['01','Nhóm khảo sát nghiệp vụ','Xác định phạm vi cấp tiểu đoàn, quy trình kiểm tra và thi vét.'],['02','Đối chiếu hai báo cáo','Chắt lọc môn theo đợt, tiêu chuẩn có hiệu lực, trạng thái vắng và người chấm.'],['03','AI phản biện mô hình','Rà soát 9 quan hệ, 12 liên kết và tính toàn vẹn lịch sử.'],['04','Nhóm thẩm định và quyết định','Chỉ nhận ý phù hợp; chưa thêm lịch sử điều chuyển và buổi kiểm tra để tránh quá phạm vi.']]; return <div><SectionHead tag="AI USAGE TRANSPARENCY" title="Nhật Ký Người Làm Và AI Hỗ Trợ">Nhóm giữ vai trò chủ thiết kế; hai báo cáo là nguồn tham khảo, AI chỉ hỗ trợ tổng hợp và phản biện.</SectionHead><div className="xmta-ai-summary"><div><span>MÔ HÌNH AI</span><strong>Fable 5 + Astra 6</strong><small>Phân tích nghiệp vụ · Rà soát ER · Kiểm tra chuẩn hóa</small></div><div><span>NGUỒN ĐỐI CHIẾU</span><strong>2 báo cáo</strong><small>Chắt lọc có kiểm chứng · Không sao chép máy móc</small></div><div><span>NGUYÊN TẮC</span><strong>Human in control</strong><small>Không tự động chấp nhận đề xuất AI</small></div></div><div className="xmta-ai-log">{sessions.map(([n,a,b])=><article key={n}><b>{n}</b><div><h3>{a}</h3><p>{b}</p></div></article>)}</div><div className="xmta-ai-decisions"><section><h3>Ý được chấp nhận</h3><ul><li>Danh sách môn cấu hình riêng theo từng đợt.</li><li>Tiêu chuẩn theo giới tính, tuổi và thời gian hiệu lực.</li><li>Phân biệt có mặt, vắng có phép, vắng không phép.</li><li>Lưu người chấm, thời điểm và quy tắc tổng hợp theo đợt.</li></ul></section><section><h3>Ý tạm chưa đưa vào</h3><ul><li>Lịch sử điều chuyển đơn vị — chưa thuộc phạm vi.</li><li>Tách buổi kiểm tra và phân công ba ngôi — để giai đoạn mở rộng.</li><li>Theo dõi GPS hoặc dinh dưỡng — ngoài bài toán.</li><li>Để AI thay kết luận chỉ huy — sai thẩm quyền.</li></ul></section></div></div> }

function Scenarios() { const cases=[['Môn theo từng đợt','Chỉ ghi kết quả cho cặp MaDot–MaMon đã tồn tại trong NOI_DUNG_DOT.'],['Tiêu chuẩn đúng phiên bản','Chọn ngưỡng theo môn, giới tính, tuổi và hiệu lực tại ngày kiểm tra.'],['Xử lý vắng mặt','VANG_CO_PHEP không bị âm thầm quy thành KHONG_DAT như VANG_KHONG_PHEP.'],['Người chấm hợp lệ','MaNguoiCham phải là quân nhân/cán bộ tồn tại và được truy vết cùng thời điểm ghi nhận.'],['Thi vét lần sau','Chỉ tạo khi lần trước cùng quân nhân, đợt và môn chưa đạt; không ghi đè lịch sử.'],['Tổng hợp cấu hình','Dùng tỷ lệ đạt và số môn không đạt tối đa của đợt, không viết cứng 4/5.'],['Tách quyền kết luận','DeXuatAI không thay thế GhiChuChiHuy.']]; return <div><SectionHead tag="TESTING & INTEGRITY" title="Bảy Tình Huống Kiểm Chứng">Các ca kiểm thử chắt lọc từ hai báo cáo và bám sát phạm vi XMTA.</SectionHead><div className="xmta-scenario-grid">{cases.map(([a,b],i)=><article key={a}><span>TC-{String(i+1).padStart(2,'0')}</span><CheckCircle2/><h3>{a}</h3><p>{b}</p></article>)}</div></div> }

function Conclusion() { return <div><SectionHead tag="KẾT LUẬN" title="XMTA Sẵn Sàng Cho Giai Đoạn Hiện Thực Hóa">Mô hình đã được đối chiếu với hai báo cáo tham khảo và giữ lại các ý có giá trị nghiệp vụ rõ ràng.</SectionHead><div className="xmta-conclusion"><ShieldCheck size={60}/><h3>Thiết kế linh hoạt hơn nhưng vẫn đúng phạm vi cấp tiểu đoàn</h3><p>Chín quan hệ đạt 3NF/BCNF, có 12 liên kết nghiệp vụ; môn kiểm tra thay đổi theo đợt, tiêu chuẩn có phiên bản, trạng thái vắng và người chấm được truy vết; AI chỉ đề xuất, chỉ huy giữ quyền kết luận.</p><div><span>9 quan hệ chuẩn hóa</span><span>12 liên kết nghiệp vụ</span><span>Tiêu chuẩn có hiệu lực</span><span>Thi vét không ghi đè</span></div></div></div> }

export default function XmtaApp({ onBack }) {
  const [section,setSection]=useState('overview'); const [theme,setTheme]=useState(()=>localStorage.getItem('smta-theme')||'dark');
  const [presentationMode,setPresentationMode]=useState(false); const [presentationPlaying,setPresentationPlaying]=useState(false); const [presentationSpeed,setPresentationSpeed]=useState(1);
  const go=id=>{setSection(id);window.scrollTo({top:0,behavior:'smooth'})};
  React.useEffect(()=>{document.documentElement.dataset.theme=theme;localStorage.setItem('smta-theme',theme)},[theme]);
  React.useEffect(()=>{if(!presentationMode||!presentationPlaying)return undefined;let frame,last=performance.now(),bottomAt=null;const animate=now=>{const delta=Math.min((now-last)/1000,.05);last=now;const max=Math.max(0,document.documentElement.scrollHeight-window.innerHeight);if(window.scrollY<max-3){bottomAt=null;window.scrollBy(0,42*presentationSpeed*delta)}else{bottomAt??=now;if(now-bottomAt>1100/presentationSpeed){const index=XMTA_SECTIONS.findIndex(item=>item[0]===section);if(index<XMTA_SECTIONS.length-1){setSection(XMTA_SECTIONS[index+1][0]);window.scrollTo({top:0,behavior:'instant'});return}else{setPresentationPlaying(false);return}}}frame=requestAnimationFrame(animate)};frame=requestAnimationFrame(animate);return()=>cancelAnimationFrame(frame)},[presentationMode,presentationPlaying,presentationSpeed,section]);
  const content={overview:<Overview go={go}/>,actors:<Actors/>,workflow:<Workflow/>,entities:<Entities/>,er:<ERGallery/>,relational:<RelationalModel/>,dictionary:<Dictionary/>,scenarios:<><Scenarios/><Results/></>,ai:<AILog/>,conclusion:<Conclusion/>}[section];
  const navSections=XMTA_SECTIONS.map(([id,num,title],index)=>({id,num,title,icon:ICONS[index]})); const current=navSections.find(item=>item.id===section)||navSections[0]; const currentIndex=navSections.findIndex(item=>item.id===section); const progress=Math.round(((currentIndex+1)/navSections.length)*100);
  const startPresentation=()=>{setPresentationMode(true);setPresentationPlaying(true);setSection('overview');window.scrollTo({top:0,behavior:'instant'})}; const stopPresentation=()=>{setPresentationPlaying(false);setPresentationMode(false)};
  return <div className="app-container xmta-app">
    <aside className="sidebar xmta-unified-sidebar">
      <div className="sidebar-header"><div className="logo-icon xmta-unified-logo"><Activity size={23}/></div><div className="logo-text"><h1>XMTA</h1><p>Quản Lý Thể Lực</p></div></div>
      {presentationMode&&<div className="presentation-progress"><div className="presentation-progress__label"><span>TIẾN TRÌNH THUYẾT TRÌNH</span><span className="mono-font">{progress}%</span></div><div className="presentation-progress__track"><div className="presentation-progress__value" style={{width:`${progress}%`}}/></div></div>}
      <nav className={`sidebar-nav ${presentationMode?'is-presenting':''}`}>{navSections.map(item=>{const Icon=item.icon;const active=section===item.id;return <button key={item.id} className={`nav-item ${active?'active':''}`} aria-current={active?'page':undefined} onClick={()=>go(item.id)}><span className="nav-num">{item.num}</span><Icon size={17}/><span className="nav-label">{item.title}</span></button>})}</nav>
      <div className="sidebar-footer"><button onClick={()=>presentationMode?stopPresentation():startPresentation()} className={`btn ${presentationMode?'btn-primary':'btn-secondary'}`} style={{width:'100%',fontSize:'.82rem',padding:'8px 12px'}}><Play size={15}/>{presentationMode?'Dừng Trình Chiếu':'Bắt Đầu Báo Cáo'}</button><div style={{display:'flex',gap:6,marginTop:8}}><button onClick={()=>{stopPresentation();setSection('overview');window.scrollTo({top:0,behavior:'smooth'})}} className="btn btn-secondary" style={{flex:1,fontSize:'.78rem',padding:'6px 8px'}}><RotateCcw size={14}/>Khôi Phục</button><button onClick={onBack} className="btn btn-secondary" style={{flex:1,fontSize:'.78rem',padding:'6px 8px'}}><ArrowLeft size={14}/>Đổi Hệ</button></div></div>
    </aside>
    <div className="main-wrapper">
      <header className="top-bar"><div className="top-bar-left"><span className="badge-military xmta-badge"><Sparkles size={12}/>XMTA v1.0 • BÁO CÁO HỌC THUẬT</span><div className="xmta-breadcrumb"><span>Đồ án CSDL</span><ChevronRight size={14}/><strong>Mục {current.num}: {current.title}</strong></div></div><div className="top-bar-right"><button onClick={onBack} className="btn btn-secondary btn-sm"><ArrowLeft size={14}/>Đổi hệ thống</button><button className="theme-toggle" onClick={()=>setTheme(v=>v==='dark'?'light':'dark')} aria-label="Đổi giao diện"><span className={theme==='dark'?'is-active':''}><Moon size={14}/></span><span className={theme==='light'?'is-active':''}><Sun size={14}/></span></button></div></header>
      <main className="content-body"><div key={section} className="section-view section-page-transition">{content}</div></main>
    </div>
    {presentationMode&&<PresentationController currentSection={section} onSelectSection={go} isPlaying={presentationPlaying} speed={presentationSpeed} onTogglePlaying={()=>setPresentationPlaying(value=>!value)} onSpeedChange={setPresentationSpeed} onExit={stopPresentation} sections={navSections}/>}<WelcomeModal system="xmta"/>
  </div>;
}
